[build]
  command = "yarn build:all"
  publish = "dist" # 기본 React 앱 경로

# Storybook을 별도 경로로 라우팅
[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200

# micro front remoteEntry 별도 경로로 라우팅
[[redirects]]
  from = "/micro/remoteEntry.js"
  to = "/micro/remoteentry.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
