[build]
  command = "yarn build:all"
  publish = "dist" # 기본 React 앱 경로

[[redirects]]
  from = "/storybook/mf/*"
  to = "/storybook/mf/:splat"
  status = 200
  force = true

# Storybook을 별도 경로로 라우팅
[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200

# 정적 파일 헤더 설정
[[headers]]
  for = "/storybook/mf/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
