[build]
  command = "yarn storybook:build:all"
  publish = "dist" # 기본 React 앱 경로

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

# Webpack 생성 파일들에 대한 MIME Type 설정
[[headers]]
  for = "/mf/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/mf/remoteentry.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Access-Control-Allow-Origin = "*"

# 정적 파일 먼저 처리
[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/mf/*"
  to = "/mf/:splat"
  status = 200
  force = true

# Storybook을 별도 경로로 라우팅
[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
