[build]
  command = "yarn build:all"
  publish = "dist" # 기본 React 앱 경로

# Webpack 생성 파일들에 대한 MIME Type 설정
[[headers]]
  for = "/storybook/mf/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/storybook/mf/remoteentry.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/storybook/mf/*"
  to = "/storybook/mf/:splat"
  status = 200
  force = true

# Storybook을 별도 경로로 라우팅
[[redirects]]
  from = "/storybook/*"
  to = "/storybook/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
